import { prisma } from "../config/prisma.js";
import { ok, fail } from "../utils/response.js";
const publicDoctor = { include: { user: { select: { firstName: true, lastName: true } }, doctorhospital: { include: { hospital: true } }, doctorservice: { include: { service: true } } } };
export async function doctors(req, res) { const { search, specialty, region, language, homeService, onlineConsultation } = req.query; const where = { ...(specialty ? { specialty } : {}), ...(homeService ? { homeService: homeService === "true" } : {}), ...(onlineConsultation ? { onlineConsultation: onlineConsultation === "true" } : {}), ...(language ? { languages: { array_contains: language } } : {}), ...(search ? { OR: [{ specialty: { contains: search, mode: "insensitive" } }, { user: { is: { firstName: { contains: search, mode: "insensitive" } } } }] } : {}), ...(region ? { doctorhospital: { some: { hospital: { region } } } } : {}) }; return ok(res, await prisma.doctor.findMany({ where, ...publicDoctor })); }
export async function doctor(req, res) { const data = await prisma.doctor.findUnique({ where: { id: req.params.id }, ...publicDoctor }); return data ? ok(res, data) : fail(res, "Doctor not found", "NOT_FOUND", 404); }
export async function doctorHospitals(req, res) { return ok(res, await prisma.doctorhospital.findMany({ where: { doctorId: req.params.id, isActive: true }, include: { hospital: true } })); }
export async function doctorServices(req, res) { return ok(res, await prisma.doctorservice.findMany({ where: { doctorId: req.params.id }, include: { service: true } })); }
export async function availability(req, res) { const hospitalId = req.query.hospitalId; return ok(res, await prisma.doctoravailability.findMany({ where: { doctorId: req.params.id, ...(hospitalId ? { hospitalId } : {}), isActive: true }, orderBy: [{ dayOfWeek: "asc" }, { startTime: "asc" }] })); }
export async function hospitalDoctors(req, res) { return ok(res, await prisma.doctorhospital.findMany({ where: { hospitalId: req.params.id, isActive: true }, include: { doctor: { include: { user: { select: { firstName: true, lastName: true } } } } } })); }
export async function hospitalServices(req, res) { return ok(res, await prisma.hospitalservice.findMany({ where: { hospitalId: req.params.id }, include: { service: true } })); }
export async function hospitalAppointments(req, res) { return ok(res, await prisma.appointment.findMany({ where: { hospitalId: req.params.id, status: { in: ["PENDING", "CONFIRMED"] } }, include: { doctor: { include: { user: { select: { firstName: true, lastName: true } } } }, patient: { include: { user: { select: { firstName: true, lastName: true } } } }, service: true }, orderBy: { date: "asc" } })); }
export async function serviceDoctors(req, res) { return ok(res, await prisma.doctorservice.findMany({ where: { serviceId: req.params.id }, include: { doctor: { include: { user: { select: { firstName: true, lastName: true } } } } } })); }
export async function serviceHospitals(req, res) { return ok(res, await prisma.hospitalservice.findMany({ where: { serviceId: req.params.id }, include: { hospital: true } })); }
export async function hospitals(req, res) { const { search, region, district } = req.query; return ok(res, await prisma.hospital.findMany({ where: { isActive: true, ...(region ? { region } : {}), ...(district ? { district } : {}), ...(search ? { name: { contains: search, mode: "insensitive" } } : {}) } })); }
export async function hospital(req, res) { const data = await prisma.hospital.findUnique({ where: { id: req.params.id }, include: { doctorhospital: { include: { doctor: { include: { user: true } } } }, hospitalservice: { include: { service: true } } } }); return data ? ok(res, data) : fail(res, "Hospital not found", "NOT_FOUND", 404); }
export async function services(req, res) { const search = req.query.search; return ok(res, await prisma.service.findMany({ where: { isActive: true, ...(search ? { name: { contains: search, mode: "insensitive" } } : {}) } })); }
export async function service(req, res) { const data = await prisma.service.findUnique({ where: { id: req.params.id } }); return data ? ok(res, data) : fail(res, "Service not found", "NOT_FOUND", 404); }
